### ISSUE TITLE
Liberty: [err] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by Karm** [eclipse/microprofile-starter#333] opened 2020-09-07 14:38 UTC
```
[err] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[err] SLF4J: Defaulting to no-operation (NOP) logger implementation
[err] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

# Reproduce
```
curl -O -J 'https://start.microprofile.io/api/project?supportedServer=LIBERTY&selectedSpecs=REST_CLIENT&selectedSpecs=JWT_AUTH&artifactId=liberty_jwt_rest'
```

JDK: OpenJDK, HotSpot 11.0.8+10  (11.0.8 GA).  it does not show with e.g. OpenJ9 11.0.5+10.

**Comment by Emily-Jiang** [comment] 2020-09-07 16:44
It looks my fix here https://github.com/eclipse/microprofile-starter/blob/master/src/main/resources/pom-servers.xml#L223 was not picked up. @rdebusscher do you know why the dependency I added from line 223 is not picked up? I can see the dependency prior to 223 was picked up.

**Comment by rdebusscher** [comment] 2020-09-09 06:34
Duplicate of #310?  PR #319 is not yet live.

**Comment by Emily-Jiang** [comment] 2020-09-09 10:34
Thanks @rdebusscher ! I thought @Karm pushed #310 to the test as it was merged. Am I right to say all merged PRs will pop up in the test-start.microprofile.io? This explains the misertery. @Karm can you get #319 to the test server?

**Comment by Karm** [comment] 2020-09-09 11:14
The automated push hasn't been happening for a while due to failing Liberty tests (unexpected error messages debated on the call).  I will temporarily disable Liberty tests so as the machinery of automated published merges works again.

https://github.com/eclipse/microprofile-starter/pull/334

**Comment by Emily-Jiang** [comment] 2020-09-28 09:13
I tested against the test server and I think I have fixed this.

**Closed by Emily-Jiang** 2020-09-28 09:13 UTC
